[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npx serve dist -s -l $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"